apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kic-consumer-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","list","watch"]
- apiGroups: ["configuration.konghq.com"]
  resources: ["kongconsumers","kongplugins","kongclusterplugins","kongingresses"]
  verbs: ["get","list","watch","update","patch"]
- apiGroups: ["configuration.konghq.com"]
  resources: ["kongconsumers/status"]
  verbs: ["get","update","patch"]
